img_search_w = "" +
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAA" +
    "DDPmHLAAAABmJLR0QAAAAAAAD5Q7t/AAAACXBIWXMAAAsTAAALEwEAmpwYAA" +
    "AAB3RJTUUH4AcSBiw3F6FANQAAAmhJREFUeNrt3UF2wyAMRdHA/vecjjrpoK" +
    "dJHSzp37cCkB4CjG0eDwAAAAAAAAAAAAAAMI3VsdHP5/N5SefXWgQISjghmg" +
    "lwKvHJIiyJzxZhSXy2CEvis0VYkp8twZL4bBGW5GdLsDon/90EVGhDpABXBP" +
    "4TAf9vuzpLsDok/1SAO7SxpQDvBvauoHZrb2kBugYzRYJVLYjVAjihD7+xba" +
    "sy9vvHK8CrI6d6oKf156MCTA3WxH7dPgV0KrEOgy4eJV0DOqmP22jKrgT7rp" +
    "GRQvWYbCMouwqs06ZPW0h17/d+IJqjAozcRv2xT1XXApcIYPGnAkTTubJtQV" +
    "IBlP/gZwKmgPAKtwXHFAACgAAgAPLWOgQI3woSwBQAAoAAyFwoEmDwAo8AIA" +
    "AIgLsF8M6ACmABOFUAZ/29Y7WNEFMAguUmQPq0dHoU+DZQBcDECpBYBSb0d1" +
    "cOnIVfMwE8E7ALiBhBk34StQQou2+7U0C1tUkFeCdYfhU7rAK8GoDKo2vyOc" +
    "YW6M+0qc1diFUD2PXCCLuAARJcPXorS+DSqENlu6oEra6N+1QQT83XJW9ESZ" +
    "1b71qkVZNg3NWxPwNccTVeSQKXR4dLMGKrRYKmAnQT4Tthky6fbn9J410jdY" +
    "oE5bYl1ST4LTkTJBh1AnfH/NxdgpEXNp5OQGcJ2r3DV/U5fVcJIj7S6HiWcK" +
    "rN3uINl4AA4RIQIFwCAoRLQIBwCQgQLgEBwiUgQLgEBAiXgADhEvhFzA1Uei" +
    "eQAOESmAIaTwfWAMES2AUES+A5QLAEngQGS+AsIFgCp4HBEvj/IgAAAAAAAA" +
    "AAAAAAeIUveAGkmcSF8AsAAAAASUVORK5CYII=";
